import type { Metadata } from "next";
import "./globals.css";
// import type { AppProps } from "next/app";
// import { SessionProvider } from "next-auth/react";
import Sidebar from "@/components/Sidebar";
import FollowBar from "@/components/FollowBar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
   title: "X platform",
   description: "Generated by Bartosz",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="pl">
         <body className={`antialiased`}>
            {/* <SessionProvider session={pageProps.session}> */}
            <RegisterModal />
            <LoginModal />
            <Toaster />
            <div className="h-screen bg-black">
               <div className="container h-full mx-auto xl:px-32 max-w-7xl">
                  <div className="grid grid-cols-4 h-full">
                     <Sidebar />
                     <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
                        {children}
                     </div>
                     <FollowBar />
                  </div>
               </div>
            </div>
            {/* </SessionProvider> */}
         </body>
      </html>
   );
}
