import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import FollowBar from "@/components/FollowBar";

export const metadata: Metadata = {
   title: "X platform",
   description: "Generated by Bartosz",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="pl">
         <body className={`antialiased`}>
            <div className="h-screen bg-black">
               <div className="container h-full mx-auto xl:px-32 max-w-7xl">
                  <div className="grid grid-cols-4 h-full">
                     <Sidebar />
                     <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
                        {children}
                     </div>
                     <FollowBar />
                  </div>
               </div>
            </div>
         </body>
      </html>
   );
}
